# Generated by Django 5.0.6 on 2024-05-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="emotion",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
